### PR TITLE
added some project and client calls

### PR DESCRIPTION
**Pull request by izzylys**

### CODE REVIEW

**Comment by tsvilans** [comment]
Looks good, and good shout on the new-style string formatting. Will implement that in the rest of the client code going forward.

One thing: in `ProjectGetAllAsync(self, query="")` you're missing `+ query` to the URL construction, but this can be added later. Flagged as TODO for later.

Thanks for the help!

**Comment by izzylys** [comment]
Ah whoops my bad! That one might not need another input actually as it gets all projects for the user?

No problem at all; happy to help!

**Comment by tsvilans** [comment]
Queries allow you to filter the results, i.e. something like `?name=Foo&num_users=10` would return only the projects named `Foo` with 10 users. This applies to most Speckle API calls (get all objects, streams, etc.), so it's very handy for getting only the results you need.

**Comment by izzylys** [comment]
Oh I see that makes sense. Good to know, thanks for the info Tom!

**Pull request merged**
