### PR TITLE
avoid pinning versions in requirements.txt

### PR DESCRIPTION
**Pull request by MaximilianFranz**
**WARNING:** I didn't get to test the whole setup without version pinning, because of a whole bunch of errors. 

In general, however, we should avoid pinning the version in the requirements.txt, because it makes using `speckle` with other libraries difficult. Specifically, I believe PySpeckle requires `pluggy==0.11` while pytest wants `pluggy>=0.12`.

### CODE REVIEW

**Comment by AntoineDao** [comment]
I feel we are going from one extreme (hard version pinning) to the other (no version pinning). We do release software in versions for a reason (manage dependency validity and such). Would it maybe be a good middle ground to use more open version requirements? (ie: use `pluggy>=0.11` instead of `pluggy==0.11`?)

Also, woah! July! That's like... forever ago! 🤣 Did you manage to get started ok @MaximilianFranz?

**Comment by MaximilianFranz** [comment]
You're right, `pluggy>=0.11` is probably better. And jep, we did get everything up and running. However, we're not depending on PySpeckly anymore. Thanks anyways :)

**Comment by tsvilans** [comment]
Hi @MaximilianFranz and @AntoineDao is this PR still valid or should we close it?

**Comment by AntoineDao** [comment]
I would close it. We don't necessarily want strict version pinning but we definitely don't want a free for all of versions 😀

**Pull request closed without merging**
