### PR TITLE
ci(semantic release): setup semantic release

### PR DESCRIPTION
**Pull request by AntoineDao**
This will trigger build and deployments to PyPi based on commit messages. For more information
checkout this: https://blog.greenkeeper.io/introduction-to-semantic-release-33f73b117c8. I also
recommend installing commitizen: https://github.com/commitizen/cz-cli.

For this change to work the following must be done:
* Now: Tag the commit the latest version was deployed from so semantic-release can appropriately bump up the version
* Now: @tsvilans needs to dump the username and password for the PyPi account he deployed to originally [here](https://travis-ci.com/speckleworks/PySpeckle/settings). Or alternatively you can add someone else (the soon to be `speckle bot` account for example as an admin which can then dump their own access keys in Travis (encrypted of course)

* Future Commits: Semantic-release makes deployment of new code to PyPi and version management trivial but it comes at the cost of applying a rather strict commit style. This effort can be removed by using [commitizen](https://github.com/commitizen/cz-cli) which can be installed really easily on most computers like so:
> npm install -g commitizen cz-conventional-changelog && echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc

Note: you need to have NodeJS installed on your machine first.

### CODE REVIEW

**Comment by AntoineDao** [comment]
Ping'd you in this one @didimitrie to check if you'd rather use a bot account for deployments or if you're happy sticking to using a contributor's credentials to run deployments to PyPi. Also to see if `speckle bot` is a thing :robot:

**Comment by didimitrie** [comment]
Hello @AntoineDao, since i'm really out of breath now - I am happy to leave the CI runs on your turf. The speckle bot is a thing, but i really really don't have the time to do it now unfortunately - I feel a bit bad. Would love to get that going though. What do you need to do it, if you're willing & have the time?

**Comment by AntoineDao** [comment]
Yep happy to set it up for you guys. Essentially I'd need an official speckle email for the bot to be registered under on Github an other services (ie: PyPi in this case). ~After that the bot would ideally have contributor access to this repo (and whatever other repo it wants to touch).~ I can sort that last one out for this repo actually. So all I need is access to a Speckleworks email account. Only personal request, which doesn't have to be satisfied: can we call it `sir-botsalot`? 😄

**Comment by botsalot** [comment]
I exist! @AntoineDao will now set me up to run deployments on github and PyPi.

**Pull request merged**
