### PR TITLE
Dynamic schemas

### PR DESCRIPTION
**Pull request by tsvilans**
This is a pretty important one, but needs discussing.

So far, program clients such as `SpeckleBlender` have used the basic API calls to retrieve a dictionary of a Speckle resource, and done manual parsing and validation their own way.

Some time ago @AntoineDao introduced schema validation and data models using `pydantic`, which looks like it could really improve the flexibility and extensibility of the Python client.

This PR is a draft implementation of something like the element libraries that the .NET client uses: available schemas are stored in a `speckle.schemas` folder. When retrieving an object from the server, the available schemas are scanned for a match based on the incoming `type` field (Mesh, Brep, Line, Plane). The appropriate schema is applied.

This means that additional schemas could be added by users, while the Python client ships with the basic, necessary ones. 

I'm still getting familiarized with `pydantic` and the framework that @AntoineDao started, and I'm sure there is plenty of optimization, handling of inheritance, combined schemas, etc. that need to be done.

At the moment, this PR works in a simple test case. The old way still works fine side-by-side with this one, but eventually I want to change `SpeckleBlender` to this "new" way. The main change in existing code is the addition of a line in `base/resource.py` that scans for available schemas. The rest of the new stuff is separated.

Thoughts, comments, criticisms, alternatives welcome!

### CODE REVIEW

**Comment by htlcnn** [comment]
How is this different from SpeckleCoreGeometry? How would we keep them in sync?

**Comment by tsvilans** [comment]
> How is this different from SpeckleCoreGeometry? How would we keep them in sync?

This is the Python equivalent of SpeckleCoreGeometry. They would have to be maintained and kept in sync.

**Comment by AntoineDao** [comment]
I think this feature would be a great addition to this repo! I will have to [fix the testing issues](https://github.com/speckleworks/PySpeckle/issues/28) you're having before we merge it so semantic-release can work it's magic.

I've got some comments about your approach but bear in mind: I'm not a user of this library so I shouldn't have too much of a say in how it gets built!

I have some concerns about the manual implementation of these schemas.As @htlcnn pointed out these schemas are a copy of an existing schema. Re-writing them here is **a lot** of brittle code work.

In an ideal world I would imagine a Speckle Object schema implementation working something like this:

- SpeckleCoreGeometry (and any other object schema) create a [JSON Schema](https://json-schema.org/) artifact for each release
- PySpeckle either [stores](https://pypi.org/project/json-schema-to-class/) or refers to these JSON Schemas dynamically and uses them to validate incoming/outgoing objects

The approach above would require some deliberation with @didimitrie and @teocomi (who I have just invoked to this thread to distract them from all the other stuff they're working on :wink: )

What do you guys think?

**Comment by didimitrie** [comment]
Let's deliberate: 
- [x] I totally like the approach, it's the way it should actually be in kits ("pure"). 

Problems will arise though because, currently, we're like so totally not ready to generate .net classes from json schemas (more work, workarounds abound, etc) (or the other way around). Ironically that's how they were created originally (that's why the specs still have point definitions in them...). 

**Note**: I really like how [hypar's doing it](https://hypar-io.github.io/Elements/Types.html#generate-code-for-your-type). My two cents from late at night 😷 

I would say let's manually keep stuff in sync, pending @tsvilans 's judgement of development effort. The geometry object definitions have stabilised (only the conversion routines changed).

**Comment by AntoineDao** [comment]
> Problems will arise though because, currently, we're like so totally not ready to generate .net classes from json schemas

I am actually proposing you integrate with something like NJson to make the dotnet classes the "source of truth" that other languages/run times can use. We are doing this with ladybug-tools where we have some [python classes](https://github.com/ladybug-tools/honeybee-schema) that are used natively but also generate a [schema](https://www.ladybug.tools/honeybee-schema/model.html) that can be used by others.

But yeah, if this feels like it's a very distant pipe-dream then might as well implement as is for now.

As a side note, I've been wanting to get into .net so if there's some scope to user NJson to create these currently I'd happily take a look (with maybe a bit of assistance for my n00b skillz if someone has capacity).

**Comment by AntoineDao** [comment]
@tsvilans I allowed myself to push a small docker-compose change to your branch to get the tests running again. A bit rude sorry but felt easier than making a PR into your branch and then merging this PR etc...

I think a few tests are failing. Mind having a look at them before merging these changes?

**Comment by tsvilans** [comment]
@dimitrie @AntoineDao regarding SpeckleCoreGeometry:  I agree 100%, automatic generation of schemas would be great, and we should steer in that direction. For now, I'll go ahead with the manual way, which should make it easier to automate later on.

@AntoineDao regarding PR, no worries, this PR is for **all** of us ;) Noticed some activity in the other issue; does that fix these testing issues?

**Comment by tsvilans** [comment]
@AntoineDao I tried re-running the tests, and it seems to fail in `test_streams.py`:
` AssertionError: {"success": false, "message": "Error: Resource not found."}` 

I tested the `test_create` and `test_delete` functions in a script and all works fine...  is this still a leftover issue from the speckleserver docker image problems?

**Comment by AntoineDao** [comment]
¯\_(ツ)_/¯

If you can't fix it maybe it's ok to just... comment out the test...

**Review by AntoineDao — APPROVED** [review]
If you're struggling to fix the test then just comment it out (and don't let anyone know I said it was ok!) and merge the changes in :smile:

**Pull request merged**
