### PR TITLE
Add tests and fix factory methods

### PR DESCRIPTION
**Pull request by AntoineDao**
I initially wanted to run unit tests but it felt pretty weak in comparison to a set of integration tests running against actual speckle servers. This travis file and accompanying tests should now allow us to happily develop python code we know will work!

Testing locally is possible. All you need to do is run the following commands in the pyspeckle folder:
> docker-compose up -d
> python -m pytest

You'll also need to install pytest:
> pip install pytest

Travis is currently testing against Python 3.6 and whatever the latest docker container for the speckle server is. I added an issue in the speckleserver repo to get some more versions so we can run integration tests of the python client against multiple versions of the server.

https://github.com/speckleworks/SpeckleServer/issues/131

### CODE REVIEW

**Comment by AntoineDao** [comment]
Wow... Well that didn't go well. About to board a flight but will fix issues with Travis and then we should be able to happily review and merge this PR :smile:

**Comment by AntoineDao** [comment]
Success!!! Here's the travis [run](https://travis-ci.com/AntoineDao/PySpeckle/builds/114032568).

Great success

**Comment by tsvilans** [comment]
Nice one! Will review soon, just wanna take a look through the other PR.

**Pull request merged**
