### PR TITLE
feat(client): add option to use apitoken

### PR DESCRIPTION
**Pull request by tsvilans**
Add option to use `apitoken` instead of `token` for persistent authorization.

### CODE REVIEW

**Review by AntoineDao — CHANGES_REQUESTED** [review]
I reckon this is [`NOP`](https://en.wikipedia.org/wiki/NOP_(code)) code. The api doesn't care which token you use. The only reason you would want to use the long lasting token is if you are going to be injecting it directly into your header rather than logging in first.

**Comment by tsvilans** [comment]
The `token` is valid for a day, the `apitoken` is persistent. This means that the `token` expires and thus the user profile in `SpeckleCache.db` is invalidated.

**Comment by AntoineDao** [comment]
Yep I understand that. But the login code you changed takes `username` and `password` as an input. And the `token` isn't persisted anywhere outside the headers. So this specific code change doesn't do anything. Unless there's something I'm being completely blind to?

**Comment by tsvilans** [comment]
Ah ok. I looked at how `SpeckleBlender` gets a hold of the token so that it can write it to the local `SpeckleCache`, and it's by grabbing it from the client headers. Not ideal. 

A better option would be to return a dict or something with the login info, including `token` and `apitoken`.

**Comment by AntoineDao** [comment]
Ha! You were techincally using it! The client object, once you've logged in, contains a dict of all that info stored in the `me` attribute.

https://github.com/speckleworks/PySpeckle/blob/0a403747af9d5bf8469938d06a027db50e0b4026/speckle/base/client.py#L115

**Comment by tsvilans** [comment]
Using `client.me` lets us get around this by getting the `apitoken` from the client after logging in.

**Pull request closed without merging**
