### PR TITLE
Update branch to master

### PR DESCRIPTION
**Pull request by tsvilans**

### CODE REVIEW

**Comment by AntoineDao** [comment]
Nah man that's not what I meant 😄 If you refresh your local `fork` of that `branch` to master then when you push the changes back to your fork the commit should be even.

I would recommend doing so by:
1. Creating a new branch on your local fork
2. run `git pull <whatever-the-speckleworks-upstream-is-called> master`
3. re-apply your code changes
4. commit those changes

**Comment by AntoineDao** [comment]
Although, that being said this has worked. It just makes the commit history super confusing to look at 😞

**Comment by tsvilans** [comment]
Whoopsie daisy. I'll get better, I swear.

**Comment by AntoineDao** [comment]
Just me being picky tbh. Don't worry too much about it.

**Pull request merged**
